simplify validation

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -68,30 +68,12 @@ runs:
         fi
 
         if [ "${{ inputs.destination }}" == "device" ]; then
-          if [ -z "${{ inputs.certificate-base64 }}" ]; then
-            echo "Input 'certificate-base64' is required for device builds."
-            exit 1
-          fi
-
-          if [ -z "${{ inputs.certificate-password }}" ]; then
-            echo "  Input 'certificate-password' is required for device builds."
-            exit 1
-          fi
-
-          if [ -z "${{ inputs.provisioning-profile-base64 }}" ]; then
-            echo "Input 'provisioning-profile-base64' is required for device builds."
-            exit 1
-          fi
-
-          if [ -z "${{ inputs.provisioning-profile-name }}" ]; then
-            echo "Input 'provisioning-profile-name' is required for device builds."
-            exit 1
-          fi
-
-          if [ -z "${{ inputs.keychain-password }}" ]; then
-            echo "Input 'keychain-password' is required for device builds."
-            exit 1
-          fi
+          for input in "certificate-base64" "certificate-password" "provisioning-profile-base64" "provisioning-profile-name" "keychain-password"; do
+            if [ -z "${{ inputs[input] }}" ]; then
+              echo "Input '$input' is required for device builds."
+              exit 1
+            fi
+          done
         fi
       shell: bash
 
